name: Build haskell project
on: [push]
jobs:
  Build-haskell-project:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building haskell project"
      - uses: actions/checkout@v2
      - name: Installing stack from apt
        run: apt install stack
      - name: Upgrading stack
        run: stack upgrade --binary-only
      - run: stack build